# Generated by Django 2.1.7 on 2019-03-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0013_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherschedule',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherSchedule',
        ),
    ]
