# Generated by Django 2.1.7 on 2019-03-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0017_disease_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
