# Generated by Django 2.1.7 on 2019-03-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0019_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
