# Generated by Django 2.1.7 on 2019-03-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Darwin', '0020_client_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
