# Generated by Django 2.1.7 on 2019-03-27 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Darwin', '0021_auto_20190327_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profiles/default_user.jpg', upload_to='profiles')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7)),
                ('dob', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
